# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0002_sidebarentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='NewsArticle',
        ),
        migrations.AlterModelOptions(
            name='sidebarentry',
            options={'ordering': ('priority',), 'verbose_name_plural': 'sidebar entries'},
        ),
    ]
