# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0003_auto_20160113_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ('published_at',)},
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='main_text',
            new_name='body',
        ),
    ]
