# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0004_auto_20160113_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sidebarentry',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
