# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0006_recipe_subpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ('-published_at',)},
        ),
    ]
