# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0007_auto_20160115_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.ManyToManyField(to='fagun.Tag'),
        ),
    ]
