# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0009_recipe_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='EducationalArticle',
        ),
    ]
