# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0012_auto_20160126_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarentry',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
