# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0013_sidebarentry_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ('-published_at',), 'verbose_name_plural': 'news stories'},
        ),
        migrations.AlterField(
            model_name='educationalarticle',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sidebarentry',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
