# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0014_auto_20160131_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalarticle',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subpage',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
