# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fagun', '0015_auto_20160201_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarentry',
            name='slug',
        ),
        migrations.AlterField(
            model_name='educationalarticle',
            name='slug',
            field=models.SlugField(help_text='Búið til sjálfkrafa við fyrstu vistun.'),
        ),
        migrations.AlterField(
            model_name='educationalarticle',
            name='sub_title',
            field=models.CharField(blank=True, default='', help_text='Má vera tómt', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='slug',
            field=models.SlugField(help_text='Búið til sjálfkrafa við fyrstu vistun.'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='sub_title',
            field=models.CharField(blank=True, default='', help_text='Má vera tómt', max_length=200),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='slug',
            field=models.SlugField(help_text='Búið til sjálfkrafa við fyrstu vistun.'),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='sub_title',
            field=models.CharField(blank=True, default='', help_text='Má vera tómt', max_length=200),
        ),
    ]
